mp:
  messaging:
    outgoing:
      message-out:
        topic: "message-out"
    incoming:
      message-in:
        auto:
          offset:
            reset: "earliest"
        topic: "message-in"
